version: "1.0"

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_local
    platform: linux/amd64 # Ensures compatibility across Mac (Intel/ARM with Rosetta) and Windows
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql-network

  adminer:
    image: adminer:latest
    container_name: adminer_web
    platform: linux/amd64 # Ensures broad compatibility
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
      ADMINER_DESIGN: "nette" # A clean and modern theme for the interface
    networks:
      - mysql-network

volumes:
  mysql_data:

networks:
  mysql-network: